[package]
name = "rustoscap"
version = "0.1.0"
authors = ["Jan Černý <jcerny@redhat.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
crate-type = ["cdylib"]
